2025-03-02 13:29:19,865 - INFO - Running in development environment
2025-03-02 13:29:19,865 - INFO - Starting Advanced Calculator application
2025-03-02 13:29:28,497 - ERROR - An error occurred in the interactive loop
Traceback (most recent call last):
  File "/home/khadhar/IS601/Calcy/calculator/__init__.py", line 96, in start
    result = self.command_handler.execute_command(cmd, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/khadhar/IS601/Calcy/calculator/commands/command.py", line 46, in execute_command
    raise TypeError("Incorrect number of arguments.")
TypeError: Incorrect number of arguments.
2025-03-02 13:47:03,346 - INFO - Running in development environment
2025-03-02 13:47:03,347 - INFO - Starting Advanced Calculator application
2025-03-02 13:47:22,513 - ERROR - An error occurred in the interactive loop
Traceback (most recent call last):
  File "/home/khadhar/IS601/Calcy/calculator/__init__.py", line 95, in start
    result = self.command_handler.execute_command(cmd, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/khadhar/IS601/Calcy/calculator/commands/command.py", line 46, in execute_command
    raise TypeError("Incorrect number of arguments.")
TypeError: Incorrect number of arguments.
2025-03-02 14:07:51,458 - INFO - Running in development environment
2025-03-02 14:07:51,460 - INFO - Starting Advanced Calculator application
